#!/bin/bash  
# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
# Author: Max Tottenham <mtottenh@gmail.com>

[ $# -eq 1 -a "$1" == "--summary" ] && exit 1
read -d . hdr

if [ "$(jose fmt -q "$hdr" -SyOg clevis -g pin -u-)" != "yubikey" ]; then
    echo "JWE pin mismatch" >&2
    exit 1
fi

slot=$(jose fmt -q "$hdr" -SyOg clevis -g yubikey -g slot -Su-) || exit 1
chal=$(jose fmt -q "$hdr" -SyOg clevis -g yubikey -g chal -Su-) || exit 1
#echo "Slot: $slot" >&2
#echo "chal: $chal" >&2
if ! resp=$(ykchalresp -$slot "$chal"); then
    echo "Unable to perform challenge response with Yubikey for slot $slot" >&2
    exit 1
fi
#echo "Resp was: $resp" >&2
key=$(echo -n "$resp" | jose pbkdf2 -i- -a S256 | jose b64 enc -I- -o-) || exit 1
#echo "Key is: $key" >&2

jwk=$(jose jwk gen -i '{ "alg" : "A256GCM" }')
jwk=$(jose fmt -j $jwk -O -q "$key" -Ss k -Uo-) || exit 1
#echo "Using JWK: $jwk" >&2
jose jwe dec -k- -i- < <(echo -n "${jwk}${hdr}."; cat)
